web:
  last_stable_version: 'master'
  protected_access: false
  eshop_url: 'https://obchod.altar.cz/'
  menu_position_fixed: true
  show_home_button: false
  name: 'TÄ›Å¡Ã­me se na vylÃ­hnutÃ­'
  title_smiley: 'ğŸ£'
  show_debug_contacts: false
application:
  yaml_file_with_routes: 'routes.yml'
google:
  analytics_id: 'UA-121206931-1'